# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false

staging:
  <<: *default
  database: stagehand_staging

production:
  <<: *default
  database: stagehand_production
