test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stagehand_staging
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stagehand_production
  username: root
  password: ''
